<a href="https://www.kaggle.com/code/sabbirhardworker/mlb-2-class-6-assignment-fba7bb?scriptVersionId=348042055" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [3]:
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/sumanthvrao/daily-climate-time-series-data/DailyDelhiClimateTrain.csv
/kaggle/input/datasets/sumanthvrao/daily-climate-time-series-data/DailyDelhiClimateTest.csv
/kaggle/input/datasets/binib1997/superstore/Superstore.csv
/kaggle/input/datasets/himanshunakrani/iris-dataset/iris.csv
/kaggle/input/datasets/saurabhbadole/restaurant-tips-dataset/tips.csv
/kaggle/input/datasets/lovishbansal123/titanic-dataset/Titanic-Dataset.csv

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# import datasets on a dataframe

In [5]:
store = pd.read_csv('/kaggle/input/datasets/binib1997/superstore/Superstore.csv', encoding='latin-1')
titanic = pd.read_csv('/kaggle/input/datasets/lovishbansal123/titanic-dataset/Titanic-Dataset.csv')
iris = pd.read_csv('/kaggle/input/datasets/himanshunakrani/iris-dataset/iris.csv')
tips = pd.read_csv('/kaggle/input/datasets/saurabhbadole/restaurant-tips-dataset/tips.csv')
climate = pd.read_csv('/kaggle/input/datasets/sumanthvrao/daily-climate-time-series-data/DailyDelhiClimateTrain.csv')

# Series

# 1. Create a series from a list

In [6]:

my_list = [10, 20, 30, 40, 50]
series_list = pd.Series(my_list)
print(series_list)

0    10
1    20
2    30
3    40
4    50
dtype: int64

# 2. Create series from a dictionary

In [7]:

my_dict = {'math': 87, 'eng': 96, 'sci': 67}
series_dict = pd.Series(my_dict)
print(series_dict)

math    87
eng     96
sci     67
dtype: int64

# 3. Create a series from dataframe

In [8]:

series_df = tips['total_bill']
print(series_df.head())

0    16.99
1    10.34
2    21.01
3    23.68
4    24.59
Name: total_bill, dtype: float64

# 4. Apply below operations on a series to understand about a series

In [9]:
# head
# tail
# sample
# size
# dtype
# astype
# index
# values

In [10]:
print("Head:\n", series_df.head(2))
print("\nTail:\n", series_df.tail(2))
print("\nSample:\n", series_df.sample(2))
print("\nSize:", series_df.size)
print("\nDtype:", series_df.dtype)
print("\nAstype:\n", series_df.astype(int).head(2))
print("\nIndex:\n", series_df.index)
print("\nValues:\n", series_df.values[:2])

Head:
 0    16.99
1    10.34
Name: total_bill, dtype: float64

Tail:
 242    17.82
243    18.78
Name: total_bill, dtype: float64

Sample:
 201    12.74
158    13.39
Name: total_bill, dtype: float64

Size: 244

Dtype: float64

Astype:
 0    16
1    10
Name: total_bill, dtype: int64

Index:
 RangeIndex(start=0, stop=244, step=1)

Values:
 [16.99 10.34]

# 5. Change data-type of a series

In [11]:

series_df = series_df.astype('float32')
print(series_df.dtype)

float32

# 6. Apply below mathematical operations on a series

In [12]:
# count
# sum
# product
# min
# max
# mean
# median
# mode
# describe
# std
# var

In [13]:
print("Count:", series_df.count())
print("Sum:", series_df.sum())
print("Product:", series_df.product())
print("Min:", series_df.min())
print("Max:", series_df.max())
print("Mean:", series_df.mean())
print("Median:", series_df.median())
print("Mode:\n", series_df.mode())
print("Describe:\n", series_df.describe())
print("Std:", series_df.std())
print("Var:", series_df.var())

Count: 244
Sum: 4827.7695
Product: inf
Min: 3.069999933242798
Max: 50.810001373291016
Mean: 19.78594
Median: 17.795000076293945
Mode:
 0    13.42
Name: total_bill, dtype: float32
Describe:
 count    244.000000
mean      19.785940
std        8.902413
min        3.070000
25%       13.347500
50%       17.795000
75%       24.127500
max       50.810001
Name: total_bill, dtype: float64
Std: 8.902413368225098
Var: 79.25296020507812

/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:56: RuntimeWarning: overflow encountered in reduce
  return umr_prod(a, axis, dtype, out, keepdims, initial, where)

# 7. Do 3 slicing operations on a series

In [14]:
print(series_df[:5])
print(series_df[10:15])
print(series_df[::2].head())

0    16.99
1    10.34
2    21.01
3    23.68
4    24.59
Name: total_bill, dtype: float32
10    10.270000
11    35.259998
12    15.420000
13    18.430000
14    14.830000
Name: total_bill, dtype: float32
0    16.99
2    21.01
4    24.59
6     8.77
8    15.04
Name: total_bill, dtype: float32

# Dataframe

# 1. Create a dataframe from a list

In [15]:
ls = [[95, 78, 56], [45, 78, 63], [90, 58, 96]]
col = ['math', 'ban', 'eng']
nums = pd.DataFrame(ls, columns=col)
print(nums)

   math  ban  eng
0    95   78   56
1    45   78   63
2    90   58   96

# 2. Apply below dataframe understanding operations

In [16]:
# head
# tail
# sample
# info
# isnull
# duplicated

In [17]:

display(titanic.head())
display(titanic.tail())
display(titanic.sample())

titanic.info()

print("Null Values:\n", titanic.isnull().sum())

print("\nDuplicated Rows:", titanic.duplicated().sum())

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
50,51,0,3,"Panula, Master. Juha Niilo",male,7.0,4,1,3101295,39.6875,NaN,S

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
Null Values:
 PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

Duplicated Rows: 0

# 2. Apply below dataframe attribute operations

In [18]:
# shape
# dtypes
# columns
# values

In [19]:
print("Shape:\n", titanic.shape)

print("\nDtypes:\n", titanic.dtypes)

print("\nColumns:\n", titanic.columns)

print("\nValues:\n", titanic.values)

Shape:
 (891, 12)

Dtypes:
 PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

Columns:
 Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

Values:
 [[1 0 3 ... 7.25 nan 'S']
 [2 1 1 ... 71.2833 'C85' 'C']
 [3 1 3 ... 7.925 nan 'S']
 ...
 [889 0 3 ... 23.45 nan 'S']
 [890 1 1 ... 30.0 'C148' 'C']
 [891 0 3 ... 7.75 nan 'Q']]

# 3. Apply below mathematical operations on a feature taken from dataframe

In [20]:
# count
# sum
# product
# min
# max
# mean
# median
# mode
# describe
# std
# var

In [21]:

feature = tips['total_bill']

print("Count:\n", feature.count())

print("\nSum:\n", feature.sum())

print("\nProduct:\n", feature.product())

print("\nMin:\n", feature.min())

print("\nMax:\n", feature.max())

print("\nMean:\n", feature.mean())

print("\nMedian:\n", feature.median())

print("\nMode:\n", feature.mode())

print("\nDescribe:\n", feature.describe())

print("\nStd:\n", feature.std())

print("\nVar:\n", feature.var())

Count:
 244

Sum:
 4827.77

Product:
 1.9053492390275928e+306

Min:
 3.07

Max:
 50.81

Mean:
 19.78594262295082

Median:
 17.795

Mode:
 0    13.42
Name: total_bill, dtype: float64

Describe:
 count    244.000000
mean      19.785943
std        8.902412
min        3.070000
25%       13.347500
50%       17.795000
75%       24.127500
max       50.810000
Name: total_bill, dtype: float64

Std:
 8.902411954856856

Var:
 79.25293861397826

# Selection and filtering

In [22]:
# loc
# iloc
# isin()
# logical operation (&, |, ~)

# 1. Select 11-20th rows and total_bill and tip columns from tips dataframe

In [23]:
tips.loc[11:20, ['total_bill', 'tip']]

    total_bill   tip
11       35.26  5.00
12       15.42  1.57
13       18.43  3.00
14       14.83  3.02
15       21.58  3.92
16       10.33  1.67
17       16.29  3.71
18       16.97  3.50
19       20.65  3.35
20       17.92  4.08

# 2. Select 0-20th rows and total_bill, tip and day columns from tips dataframe

In [24]:
tips.loc[0:20, ['total_bill', 'tip', 'day']]

    total_bill   tip  day
0        16.99  1.01  Sun
1        10.34  1.66  Sun
2        21.01  3.50  Sun
3        23.68  3.31  Sun
4        24.59  3.61  Sun
5        25.29  4.71  Sun
6         8.77  2.00  Sun
7        26.88  3.12  Sun
8        15.04  1.96  Sun
9        14.78  3.23  Sun
10       10.27  1.71  Sun
11       35.26  5.00  Sun
12       15.42  1.57  Sun
13       18.43  3.00  Sun
14       14.83  3.02  Sun
15       21.58  3.92  Sun
16       10.33  1.67  Sun
17       16.29  3.71  Sun
18       16.97  3.50  Sun
19       20.65  3.35  Sat
20       17.92  4.08  Sat

# 3. Select customers who comes in sunday and total_bill is greater than 20 dollars

In [25]:
a = tips[(tips['day'] == 'Sun') & (tips['total_bill'] > 20)]
print(a.head())

   total_bill   tip     sex smoker  day    time  size
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
5       25.29  4.71    Male     No  Sun  Dinner     4
7       26.88  3.12    Male     No  Sun  Dinner     4

# 4. Select passengers who are male and age greater than 50 from titanic

In [26]:
titanic[(titanic['Sex'] == 'male') & (titanic['Age'] > 50)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
33,34,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,NaN,S
54,55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.0,0,1,113509,61.9792,B30,C
94,95,0,3,"Coxon, Mr. Daniel",male,59.0,0,0,364500,7.2500,NaN,S
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
124,125,0,1,"White, Mr. Percival Wayland",male,54.0,0,1,35281,77.2875,D26,S
150,151,0,2,"Bateman, Rev. Robert James",male,51.0,0,0,S.O.P. 1166,12.5250,NaN,S
152,153,0,3,"Meo, Mr. Alfonzo",male,55.5,0,0,A.5. 11206,8.0500,NaN,S
155,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C
170,171,0,1,"Van der hoef, Mr. Wyckoff",male,61.0,0,0,111240,33.5000,B19,S
174,175,0,1,"Smith, Mr. James Clinch",male,56.0,0,0,17764,30.6958,A7,C
222,223,0,3,"Green, Mr. George Henry",male,51.0,0,0,21440,8.0500,NaN,S
232,233,0,2,"Sjostedt, Mr. Ernst Adolf",male,59.0,0,0,237442,13.5000,NaN,S
249,250,0,2,"Carter, Rev. Ernest Courtenay",male,54.0,1,0,244252,26.0000,NaN,S
252,253,0,1,"Stead, Mr. William Thomas",male,62.0,0,0,113514,26.5500,C87,S
262,263,0,1,"Taussig, Mr. Emil",male,52.0,1,1,110413,79.6500,E67,S
280,281,0,3,"Duane, Mr. Frank",male,65.0,0,0,336439,7.7500,NaN,Q
317,318,0,2,"Moraweck, Dr. Ernest",male,54.0,0,0,29011,14.0000,NaN,S
326,327,0,3,"Nysveen, Mr. Johan Hansen",male,61.0,0,0,345364,6.2375,NaN,S
406,407,0,3,"Widegren, Mr. Carl/Charles Peter",male,51.0,0,0,347064,7.7500,NaN,S
438,439,0,1,"Fortune, Mr. Mark",male,64.0,1,4,19950,263.0000,C23 C25 C27,S
449,450,1,1,"Peuchen, Major. Arthur Godfrey",male,52.0,0,0,113786,30.5000,C104,S
456,457,0,1,"Millet, Mr. Francis Davis",male,65.0,0,0,13509,26.5500,E38,S
467,468,0,1,"Smart, Mr. John Montgomery",male,56.0,0,0,113792,26.5500,NaN,S
487,488,0,1,"Kent, Mr. Edward Austin",male,58.0,0,0,11771,29.7000,B37,C
492,493,0,1,"Molson, Mr. Harry Markland",male,55.0,0,0,113787,30.5000,C30,S
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
545,546,0,1,"Nicholson, Mr. Arthur Ernest",male,64.0,0,0,693,26.0000,NaN,S
555,556,0,1,"Wright, Mr. George",male,62.0,0,0,113807,26.5500,NaN,S
570,571,1,2,"Harris, Mr. George",male,62.0,0,0,S.W./PP 752,10.5000,NaN,S
582,583,0,2,"Downton, Mr. William James",male,54.0,0,0,28403,26.0000,NaN,S
587,588,1,1,"Frolicher-Stehli, Mr. Maxmillian",male,60.0,1,1,13567,79.2000,B41,C
625,626,0,1,"Sutton, Mr. Frederick",male,61.0,0,0,36963,32.3208,D50,S
626,627,0,2,"Kirkland, Rev. Charles Leonard",male,57.0,0,0,219533,12.3500,NaN,Q
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
631,632,0,3,"Lundahl, Mr. Johan Svensson",male,51.0,0,0,347743,7.0542,NaN,S
647,648,1,1,"Simonius-Blumer, Col. Oberst Alfons",male,56.0,0,0,13213,35.5000,A26,C
659,660,0,1,"Newell, Mr. Arthur Webster",male,58.0,0,2,35273,113.2750,D48,C
672,673,0,2,"Mitchell, Mr. Henry Michael",male,70.0,0,0,C.A. 24580,10.5000,NaN,S
684,685,0,2,"Brown, Mr. Thomas William Solomon",male,60.0,1,1,29750,39.0000,NaN,S
694,695,0,1,"Weir, Col. John",male,60.0,0,0,113800,26.5500,NaN,S
695,696,0,2,"Chapman, Mr. Charles Henry",male,52.0,0,0,248731,13.5000,NaN,S
714,715,0,2,"Greenberg, Mr. Samuel",male,52.0,0,0,250647,13.0000,NaN,S
745,746,0,1,"Crosby, Capt. Edward Gifford",male,70.0,1,1,WE/P 5735,71.0000,B22,S
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S
857,858,1,1,"Daly, Mr. Peter Denis",male,51.0,0,0,113055,26.5500,E17,S

# 5. Select customers who are female and tip greater than 5 dollars from tips dataframe - write query operation

In [27]:
tips.query("sex == 'Female' and tip > 5")

     total_bill   tip     sex smoker   day    time  size
52        34.81  5.20  Female     No   Sun  Dinner     4
85        34.83  5.17  Female     No  Thur   Lunch     4
155       29.85  5.14  Female     No   Sun  Dinner     5
214       28.17  6.50  Female    Yes   Sat  Dinner     3

# groupby

# 1. group on region based in store dataframe

In [28]:
region_group = store.groupby('Region')
region_group.size()

Region
Central    2323
East       2848
South      1620
West       3203
dtype: int64

# 2. Find region-wise average sales

In [29]:
store.groupby('Region')['Sales'].mean()

Region
Central    215.772661
East       238.336110
South      241.803645
West       226.493233
Name: Sales, dtype: float64

# 3. Find region-wise average profit

In [30]:
store.groupby('Region')['Profit'].mean()

Region
Central    17.092709
East       32.135808
South      28.857673
West       33.849032
Name: Profit, dtype: float64

# 4. Find region-wise maximum profit

In [31]:
store.groupby('Region')['Profit'].max()

Region
Central    8399.9760
East       5039.9856
South      3177.4750
West       6719.9808
Name: Profit, dtype: float64

# 5. Apply multiple aggregate functions on region-wise sales

In [32]:
store.groupby('Region')['Sales'].agg(['mean', 'sum', 'max', 'min'])

               mean          sum        max    min
Region
Central  215.772661  501239.8908  17499.950  0.444
East     238.336110  678781.2400  11199.968  0.852
South    241.803645  391721.9050  22638.480  1.167
West     226.493233  725457.8245  13999.960  0.990

# 6. group on region and category wise

In [33]:
region_cat_group = store.groupby(['Region', 'Category'])
region_cat_group.size()

Region   Category
Central  Furniture           481
         Office Supplies    1422
         Technology          420
East     Furniture           601
         Office Supplies    1712
         Technology          535
South    Furniture           332
         Office Supplies     995
         Technology          293
West     Furniture           707
         Office Supplies    1897
         Technology          599
dtype: int64

# 7. Find region and category wise average sales

In [34]:
store.groupby(['Region', 'Category'])['Sales'].mean()

Region   Category
Central  Furniture          340.534644
         Office Supplies    117.458801
         Technology         405.753124
East     Furniture          346.574383
         Office Supplies    120.044425
         Technology         495.278469
South    Furniture          353.309289
         Office Supplies    126.282727
         Technology         507.753952
West     Furniture          357.302325
         Office Supplies    116.422377
         Technology         420.687533
Name: Sales, dtype: float64

# 8. Find region and category wise average, minimumm, maximum and sum sales

In [35]:
store.groupby(['Region', 'Category'])['Sales'].agg(['mean', 'min', 'max', 'sum'])

                               mean    min        max          sum
Region  Category
Central Furniture        340.534644  1.892   3504.900  163797.1638
        Office Supplies  117.458801  0.444   9892.740  167026.4150
        Technology       405.753124  1.980  17499.950  170416.3120
East    Furniture        346.574383  2.960   4416.174  208291.2040
        Office Supplies  120.044425  0.852   4663.736  205516.0550
        Technology       495.278469  2.970  11199.968  264973.9810
South   Furniture        353.309289  2.784   4297.644  117298.6840
        Office Supplies  126.282727  1.167   6354.950  125651.3130
        Technology       507.753952  1.584  22638.480  148771.9080
West    Furniture        357.302325  3.480   3610.848  252612.7435
        Office Supplies  116.422377  1.080   8187.650  220853.2490
        Technology       420.687533  0.990  13999.960  251991.8320

# Merging and joining

In [36]:
students = pd.DataFrame({
    "student_id": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110,
                   111, 112, 113, 114, 115, 116, 117, 118, 119, 120],
    "name": ["Rahim", "Karim", "Hasan", "Sakib", "Nabil",
             "Tanvir", "Fahim", "Rafi", "Imran", "Shakil",
             "Arif", "Jahid", "Mehedi", "Siam", "Tareq",
             "Rakib", "Adnan", "Nayeem", "Foysal", "Rony"],
    "department": ["CSE", "EEE", "CSE", "BBA", "CSE",
                   "EEE", "CSE", "BBA", "CSE", "EEE",
                   "CSE", "BBA", "EEE", "CSE", "BBA",
                   "CSE", "EEE", "CSE", "BBA", "EEE"]
})

students

    student_id    name department
0          101   Rahim        CSE
1          102   Karim        EEE
2          103   Hasan        CSE
3          104   Sakib        BBA
4          105   Nabil        CSE
5          106  Tanvir        EEE
6          107   Fahim        CSE
7          108    Rafi        BBA
8          109   Imran        CSE
9          110  Shakil        EEE
10         111    Arif        CSE
11         112   Jahid        BBA
12         113  Mehedi        EEE
13         114    Siam        CSE
14         115   Tareq        BBA
15         116   Rakib        CSE
16         117   Adnan        EEE
17         118  Nayeem        CSE
18         119  Foysal        BBA
19         120    Rony        EEE

In [37]:
results = pd.DataFrame({
    "student_id": [101, 102, 103, 105, 106, 108, 109, 111, 112, 114,
                   121, 122, 123, 124, 125, 126, 127, 128, 129, 130],
    "math": [85, 72, 91, 68, 77, 88, 74, 95, 81, 69,
             78, 84, 92, 73, 89, 67, 80, 94, 76, 83],
    "python": [90, 75, 88, 72, 80, 92, 79, 96, 85, 71,
               82, 87, 95, 76, 91, 70, 84, 93, 78, 86]
})

results

    student_id  math  python
0          101    85      90
1          102    72      75
2          103    91      88
3          105    68      72
4          106    77      80
5          108    88      92
6          109    74      79
7          111    95      96
8          112    81      85
9          114    69      71
10         121    78      82
11         122    84      87
12         123    92      95
13         124    73      76
14         125    89      91
15         126    67      70
16         127    80      84
17         128    94      93
18         129    76      78
19         130    83      86

In [38]:
departments = pd.DataFrame({
    "dept_id": [1, 2, 3, 4],
    "department": [
        "CSE",
        "EEE",
        "BBA",
        "Civil"
    ],
    "faculty": [
        "Engineering",
        "Engineering",
        "Business",
        "Engineering"
    ]
})

departments

   dept_id department      faculty
0        1        CSE  Engineering
1        2        EEE  Engineering
2        3        BBA     Business
3        4      Civil  Engineering

# 1. Create a dataframe contains students name,faculty and number on math and python

In [50]:
# join of students, results, and departments table
data1 = students.merge(results, how='inner', on='student_id')
data = data1.merge(departments, how='inner', on='department')
data = data[['name', 'faculty', 'math', 'python']]
data

     name      faculty  math  python
0   Rahim  Engineering    85      90
1   Karim  Engineering    72      75
2   Hasan  Engineering    91      88
3   Nabil  Engineering    68      72
4  Tanvir  Engineering    77      80
5    Rafi     Business    88      92
6   Imran  Engineering    74      79
7    Arif  Engineering    95      96
8   Jahid     Business    81      85
9    Siam  Engineering    69      71

# 2. Department wise students count

In [52]:

data = students.merge(departments, how='inner', on='department')
data = data[['name', 'department', 'faculty']]

data.groupby('department').count()

            name  faculty
department
BBA            5        5
CSE            9        9
EEE            6        6

# 3. Faculty wise department count

In [53]:

data.groupby('faculty').count()

             name  department
faculty
Business        5           5
Engineering    15          15

# 4. Find department wise highest number on each subject

In [54]:

data1 = students.merge(results, on='student_id')
data = data1.merge(departments, on='department')

highest_marks = data[['department', 'math', 'python']].groupby('department').max()


display(highest_marks)

            math  python
department
BBA           88      92
CSE           95      96
EEE           77      80

# 5. Find faculty wise highest number on each subject

In [56]:

faculty_highest = data[['faculty', 'math', 'python']].groupby('faculty').max()

display(faculty_highest)

             math  python
faculty
Business       88      92
Engineering    95      96

# Time-series

In [40]:
# use climate dataset
climate

            date   meantemp    humidity  wind_speed  meanpressure
0     2013-01-01  10.000000   84.500000    0.000000   1015.666667
1     2013-01-02   7.400000   92.000000    2.980000   1017.800000
2     2013-01-03   7.166667   87.000000    4.633333   1018.666667
3     2013-01-04   8.666667   71.333333    1.233333   1017.166667
4     2013-01-05   6.000000   86.833333    3.700000   1016.500000
...          ...        ...         ...         ...           ...
1457  2016-12-28  17.217391   68.043478    3.547826   1015.565217
1458  2016-12-29  15.238095   87.857143    6.000000   1016.904762
1459  2016-12-30  14.095238   89.666667    6.266667   1017.904762
1460  2016-12-31  15.052632   87.000000    7.325000   1016.100000
1461  2017-01-01  10.000000  100.000000    0.000000   1016.000000

[1462 rows x 5 columns]

# 1. convert time into datetime

In [41]:
climate['date'] = pd.to_datetime(climate['date'])
climate['date'].head()

0   2013-01-01
1   2013-01-02
2   2013-01-03
3   2013-01-04
4   2013-01-05
Name: date, dtype: datetime64[ns]

# 2. set date as index

In [42]:
climate = climate.set_index('date')
climate.head()

             meantemp   humidity  wind_speed  meanpressure
date
2013-01-01  10.000000  84.500000    0.000000   1015.666667
2013-01-02   7.400000  92.000000    2.980000   1017.800000
2013-01-03   7.166667  87.000000    4.633333   1018.666667
2013-01-04   8.666667  71.333333    1.233333   1017.166667
2013-01-05   6.000000  86.833333    3.700000   1016.500000

# 3. Select row of 13 january, 2015

In [43]:
climate.loc['2015-01-13']

meantemp          12.250
humidity          77.875
wind_speed         4.875
meanpressure    1017.125
Name: 2015-01-13 00:00:00, dtype: float64

# 4. Select rows contains in april 2017

In [44]:

try:
    display(climate.loc['2017-04'])
except KeyError:
    print("No data available for April 2017 in this dataset.")

No data available for April 2017 in this dataset.

# 5. Select rows from 11 september, 2014 to 25 september, 2014

In [45]:
climate.loc['2014-09-11':'2014-09-25']

             meantemp   humidity  wind_speed  meanpressure
date
2014-09-11  26.571429  85.714286   17.825000   1005.571429
2014-09-12  28.500000  73.000000    1.625000   1005.125000
2014-09-13  29.375000  68.250000    4.162500   1004.000000
2014-09-14  29.125000  65.500000    6.712500   1004.250000
2014-09-15  29.625000  63.125000    6.712500   1004.250000
2014-09-16  30.625000  65.125000    6.250000   1002.250000
2014-09-17  30.625000  61.875000    7.400000   1002.125000
2014-09-18  30.500000  62.375000    6.712500   1003.875000
2014-09-19  31.000000  56.625000    4.175000   1003.500000
2014-09-20  31.125000  55.750000    4.400000   1002.875000
2014-09-21  30.500000  54.875000    5.562500   1003.625000
2014-09-22  30.625000  50.000000   13.437500   1004.500000
2014-09-23  31.000000  47.000000   30.685714   1004.285714
2014-09-24  29.625000  53.000000    8.100000   1006.250000
2014-09-25  30.000000  52.500000    9.725000   1007.750000

# 6. Calculate month-wise average windspeed

In [46]:
climate['wind_speed'].resample('ME').mean()

date
2013-01-31     4.833913
2013-02-28     7.474090
2013-03-31     8.757270
2013-04-30     8.046385
2013-05-31     8.943452
2013-06-30     9.593929
2013-07-31     7.358698
2013-08-31     7.384347
2013-09-30     7.593425
2013-10-31     2.836110
2013-11-30     4.252242
2013-12-31     4.986002
2014-01-31     5.560580
2014-02-28     6.402232
2014-03-31     7.123963
2014-04-30     8.868631
2014-05-31     8.576555
2014-06-30    10.111250
2014-07-31     7.528590
2014-08-31     7.665360
2014-09-30     8.054940
2014-10-31     3.988191
2014-11-30     3.126667
2014-12-31     4.133756
2015-01-31     5.261290
2015-02-28     6.317985
2015-03-31     7.701210
2015-04-30     8.530000
2015-05-31     9.065495
2015-06-30     8.769167
2015-07-31     8.580703
2015-08-31     5.477031
2015-09-30     7.229048
2015-10-31     4.930012
2015-11-30     2.117500
2015-12-31     3.795392
2016-01-31     4.285177
2016-02-29     5.950592
2016-03-31     7.204904
2016-04-30     9.687357
2016-05-31     9.506423
2016-06-30     9.052079
2016-07-31     6.207018
2016-08-31     7.168392
2016-09-30     7.508029
2016-10-31     7.291021
2016-11-30     5.993723
2016-12-31     6.132705
2017-01-31     0.000000
Freq: ME, Name: wind_speed, dtype: float64

# 7. Calculate month-wise highest meantemp

In [47]:
climate['meantemp'].resample('ME').max()

date
2013-01-31    16.500000
2013-02-28    20.800000
2013-03-31    29.166667
2013-04-30    32.125000
2013-05-31    38.714286
2013-06-30    37.166667
2013-07-31    33.857143
2013-08-31    32.500000
2013-09-30    32.750000
2013-10-31    30.833333
2013-11-30    23.428571
2013-12-31    18.000000
2014-01-31    16.625000
2014-02-28    19.625000
2014-03-31    26.250000
2014-04-30    33.250000
2014-05-31    35.250000
2014-06-30    38.500000
2014-07-31    36.625000
2014-08-31    34.125000
2014-09-30    31.250000
2014-10-31    31.000000
2014-11-30    24.125000
2014-12-31    25.000000
2015-01-31    15.125000
2015-02-28    23.125000
2015-03-31    28.500000
2015-04-30    32.875000
2015-05-31    37.750000
2015-06-30    37.625000
2015-07-31    35.714286
2015-08-31    32.625000
2015-09-30    33.000000
2015-10-31    30.000000
2015-11-30    24.000000
2015-12-31    19.250000
2016-01-31    20.142857
2016-02-29    23.875000
2016-03-31    30.000000
2016-04-30    35.687500
2016-05-31    38.272727
2016-06-30    38.200000
2016-07-31    34.187500
2016-08-31    33.809524
2016-09-30    33.444444
2016-10-31    33.269231
2016-11-30    25.640000
2016-12-31    21.208333
2017-01-31    10.000000
Freq: ME, Name: meantemp, dtype: float64

# 8. Year-wise maximum, minimum and average humidity

In [48]:
climate['humidity'].resample('YE').agg(['max', 'min', 'mean'])

                   max         min        mean
date
2013-12-31   94.000000   15.857143   63.046292
2014-12-31   96.857143   20.875000   59.767942
2015-12-31   98.000000   13.428571   61.430490
2016-12-31   94.300000   18.466667   58.740174
2017-12-31  100.000000  100.000000  100.000000

# 9. A new column contains previous 10 days average meantemp

In [49]:
climate['prev_10_days_temp'] = climate['meantemp'].rolling(10).mean()
climate[['meantemp', 'prev_10_days_temp']].head(15)

             meantemp  prev_10_days_temp
date
2013-01-01  10.000000                NaN
2013-01-02   7.400000                NaN
2013-01-03   7.166667                NaN
2013-01-04   8.666667                NaN
2013-01-05   6.000000                NaN
2013-01-06   7.000000                NaN
2013-01-07   7.000000                NaN
2013-01-08   8.857143                NaN
2013-01-09  14.000000                NaN
2013-01-10  11.000000           8.709048
2013-01-11  15.714286           9.280476
2013-01-12  14.000000           9.940476
2013-01-13  15.833333          10.807143
2013-01-14  12.833333          11.223810
2013-01-15  14.714286          12.095238